services:
  ryu-controller:
    image: osrg/ryu
    command: ryu-manager ryu.app.simple_switch_13 ryu.app.rest_topology
    ports:
      - "6633:6633" 
      - "8080:8080" 
    networks:
      - sdn_net

  switch-ovs:
    build: .
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    depends_on:
      - ryu-controller
    networks:
      - sdn_net

networks:
  sdn_net:
    driver: bridge